n1 = float(input('Digite o valor do seu salário: '))
s = n1+(n1*0.15)
print('================================')
print('Seu novo salário com o aumento de 15% será: {}'.format(s))
print('================================')